import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientProvider } from "./QueryClientProvider";
import Navbar from "./_common/components/header";
import Footer from "./_common/components/footer";
import BackToTopButton from "./_components/back-to-top-button";
import { CartProvider } from "./_contexts/CartContext";
import { AuthProvider } from "./_contexts/AuthContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <AuthProvider>
            <CartProvider>
              <Navbar />
              {children}
            </CartProvider>
            <BackToTopButton />
          </AuthProvider>
        </ClientProvider>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
