import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClientProvider } from "./QueryClientProvider";
import Navbar from "./_common/components/header";
import Footer from "./_common/components/footer";
import BackToTopButton from "./_components/back-to-top-button";
import { CartProvider } from "./_contexts/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <Navbar />
          {/* <Link href="/clientComponent">Client component</Link>
          <Link href="/serverComponent">Server component</Link>
          <Link href="/">Home</Link>
          <Link href="/register">Register</Link>
          <Link href="/forgot-password">ForgotPassword</Link>
          <Link href="/reset-password">ResetPassword</Link> */}
          <CartProvider>
          {children}
          </CartProvider>
          <BackToTopButton/>
        </ClientProvider>
        <Footer />
      </body>
    </html>
  );
}
